nside = 512
output_folder = "output/{nside}/{tag}/0000"
output_filename_template="simonsobs_{tag}_uKCMB_{telescope}{band:03d}_nside{nside}_0000.fits"
channels = "all"
unit = "uK_CMB"
mapsims_version = "1.0.0"
so_pysm_models_version = "1.0.0"
